# Generated by Django 2.0.6 on 2019-12-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haisen', '0002_auto_20191204_0702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kakeibo',
            new_name='Haisen',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='haisen',
            options={'verbose_name': '俳句と川柳', 'verbose_name_plural': '俳句と川柳'},
        ),
        migrations.AlterModelTable(
            name='haisen',
            table='Haisen',
        ),
    ]
