# Generated by Django 2.0.6 on 2019-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haisen', '0003_auto_20191204_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haisen',
            name='category',
        ),
        migrations.RemoveField(
            model_name='haisen',
            name='date',
        ),
        migrations.RemoveField(
            model_name='haisen',
            name='memo',
        ),
        migrations.AlterField(
            model_name='haisen',
            name='money',
            field=models.IntegerField(help_text='任意の数字を入れてね', verbose_name='番号'),
        ),
    ]
