# Generated by Django 3.1.1 on 2020-11-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haisen', '0004_auto_20191214_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='haisen',
            name='money',
            field=models.CharField(max_length=500, verbose_name='ニックネーム'),
        ),
    ]
