# Generated by Django 3.1.1 on 2020-11-18 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haisen', '0005_auto_20201118_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haisen',
            name='money',
        ),
        migrations.AddField(
            model_name='haisen',
            name='haisen',
            field=models.CharField(max_length=255, null=True, verbose_name='俳句や川柳'),
        ),
        migrations.AddField(
            model_name='haisen',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='作者名'),
        ),
        migrations.AddField(
            model_name='haisen',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
