# Generated by Django 3.1.1 on 2020-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haisen', '0006_auto_20201118_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haisen',
            name='haisen',
            field=models.CharField(max_length=255, verbose_name='俳句や川柳'),
        ),
        migrations.AlterField(
            model_name='haisen',
            name='name',
            field=models.CharField(max_length=255, verbose_name='作者名'),
        ),
    ]
